In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime

In [2]:
data = {
    "Date": [
        "2026-01-05",
        "2026-01-06",
        "2026-01-07",
        "2026-01-08",
        "2026-01-09"
    ],
    "Close": [690.2, 694.1, 691.5, 697.3, 699.0],
    "Volume": [80000000, 85000000, 78000000, 90000000, 82000000]
}

df = pd.DataFrame(data)

df

         Date  Close    Volume
0  2026-01-05  690.2  80000000
1  2026-01-06  694.1  85000000
2  2026-01-07  691.5  78000000
3  2026-01-08  697.3  90000000
4  2026-01-09  699.0  82000000

In [3]:
prices = np.array(df["Close"])

prices

array([690.2, 694.1, 691.5, 697.3, 699. ])

In [4]:
mean_price = np.mean(prices)

print("Mean closing price:", mean_price)

Mean closing price: 694.4200000000001

In [5]:
df["Daily_Return"] = df["Close"].pct_change()

df

         Date  Close    Volume  Daily_Return
0  2026-01-05  690.2  80000000           NaN
1  2026-01-06  694.1  85000000      0.005651
2  2026-01-07  691.5  78000000     -0.003746
3  2026-01-08  697.3  90000000      0.008388
4  2026-01-09  699.0  82000000      0.002438